name: Docker image update for SImple Component

on:
    push:
        branches: [ master, main ]
        tags: [ 'v*.*.*' ]

    # Allows to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: simcesplatform/simple-component

jobs:

    docker-image:
        runs-on: ubuntu-20.04
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            # Workaround: https://github.com/docker/build-push-action/issues/461
            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v2.2.1

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v2.1.0
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract Docker metadata for Simple Component
              id: metadata
              uses: docker/metadata-action@v4.1.1
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Build and push Docker image for Simple Component
              id: build-and-push
              uses: docker/build-push-action@v3.2.0
              with:
                  context: .
                  file: Dockerfile
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: |
                      ${{ steps.metadata.outputs.tags }}
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                  labels: ${{ steps.metadata.outputs.labels }}
